#!/usr/bin/env python
import socket
import sys
from datetime import datetime

import result as result

import portscanner

# Ask for input
host = input("Enter host IP:")

# Print a banner with information on host we are about to scan
print("-" * 60)
print("Please wait, scanning remote host")
print("-" * 60)


# Check what time the scan started
t1 = datetime.now()
# Time needs to be mm/dd/yy and time m:m:s

# Using the range function to specify ports (here it will scans all ports between 1 and 1024)

# Also put in some error handling for catching errors
try:
    for port in range(1024, 1):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind(('0.0.0.0', 0))
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        if result == 0:
            print ("port {}:    open".format(sock))
            print('listening on port:', sock.getsockname()[1])
            result = sock.connect_ex((host, sock))
        sock.close
        sys.exit()
        break
except KeyboardInterrupt:
    print("You pressed Ctrl+C")
    sys.exit()

except socket.gaierror:
    print('Host could not be resolved. Exiting')
    sys.exit()

except socket.error:
    print("Couldn't connect to server")
    sys.exit()

# Checking the time again
t2 = datetime.now()

# Calculates the difference of time, to see how long it took to run the script
total = t2 - t1

# Printing the information to screen
print('Scanning Completed in: ', total)
print("-" * 60)
sys.e
